<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>LockersInteligentes.DAL</RootNamespace>
    <AssemblyName>LockersInteligentes.DAL</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dominio\LockersInteligentes.Dominio.csproj" />
  </ItemGroup>
  <ItemGroup>
    <!-- Unico paquete de terceros: el driver de SQL Server (no es un ORM). -->
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
  </ItemGroup>
</Project>
